### ISSUE TITLE
Alpha conversion exits adds trailing spaces

### ISSUE THREAD

**Issue by ElNovi** [SAP/abap-to-json#10]
Hi everyone! 

Thanks for this amazing library and for open sourcing it!

# Issue description

When you enable conversion exits, fields with ALPHA or similiar conversion routine seems to add trailing spaces to fill up the defined lenght of char element.

In case of vbeln (char10) for value `0001893348` it removes 3 zero leading characters, but adds trailing spaces to fill up to 10 characters -> `1893348   `

There is workaround for this by changing type to string and using ALPHA conversion manually, but it would be nice if it can be solved in this library. Or maybe i'm just using it wrong....

Currently i'm using PL18 version of `/ui2/cl_json`. 

## Minimal runnable code

```abap
    TYPES: BEGIN OF t_deliveries,
             delivery TYPE vbeln,
           END OF t_deliveries.

    DATA(deliveries) = VALUE t_deliveries( delivery = '0001893348' ).

    DATA(lv_json) = /ui2/cl_json=>serialize( data             = deliveries
                                             compress         = abap_false
                                             conversion_exits = abap_true
                                             pretty_name      = /ui2/cl_json=>pretty_mode-camel_case ).
```

## Result

`{"delivery":"1893348   "}`

## Expected result

`{"delivery":"1893348"}`

**Comment by alexey-arseniev** [comment]
Hi @ElNovi , 

I'm sorry for not getting back to you sooner. I am on vacation till the 1st of October. 

You are using all correctly and the issue is caused by recent changes I did. Before, when calling conversion exits for fields, I passed the string buffer, and all was working fine. Then there was a bug report, that some ALPHA conversions were not working with type STRING and only works with a C buffer. And I made a change that caused even more issues. But mostly on deserialization. I fixed that, by using destination type and no intermediate buffer, but left the change for serializing in (this one was mentioned in the message). 

However, later I found in the documentation that the output ALPHA conversion shall support also strings. 

In general, I may do a CONDENSE on the result to avoid trailing spaces, but this will result in performance loss. So, I am tending to just revert the logic to use STRING as an intermediate output buffer and ask the author of the ALPHA conversion from the message to extend it for strings. This shall be more efficient. 

I will publish the correction for the open-source version in October. For the official PL release (note), I am not sure when I will publish it - would like to collect more changes. 

BR, Alexey.

**Comment by alexey-arseniev** [comment]
Hi @ElNovi ,

I have reverted the change and updated the code. See also the [FAQ note for this case](https://github.com/SAP/abap-to-json/blob/main/docs/faq.md#you-get-a-short-dump-objects_not_char-when-serializing-data-with-enabled-conversion-exits).
The correction for /ui2/cl_json will be delivered with the [note](https://launchpad.support.sap.com/#/notes/3515438) (not yet released). 

Please test with the Open Source version and come back if something does not work.

BR, Alexey.

**Comment by ElNovi** [comment]
Hi,

sorry for not respoding earlier, i was busy with non-abap development and holidays. Today we downloaded note PL20 and it seems it still add trailing spaces. I tried the open source version and got the same result.

I've created this test class which outputs both the `/ui2/cl_json` and `z_ui2_json` classes.

``` abap
CLASS zcl_novakl_json DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun.

  PRIVATE SECTION.

    METHODS trailing_spaces
      RETURNING VALUE(result) TYPE string.

ENDCLASS.

CLASS zcl_novakl_json IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
    out->write( trailing_spaces( ) ).
  ENDMETHOD.

  METHOD trailing_spaces.

    TYPES: BEGIN OF t_deliveries,
             delivery TYPE vbeln_vl,
           END OF t_deliveries.

    DATA(deliveries) = VALUE t_deliveries( delivery = '0001893348' ).

    DATA(original) = /ui2/cl_json=>serialize( data             = deliveries
                                              compress         = abap_false
                                              conversion_exits = abap_true
                                              pretty_name      = /ui2/cl_json=>pretty_mode-camel_case ).

    DATA(open_source) = z_ui2_json=>serialize( data             = deliveries
                                               compress         = abap_false
                                               conversion_exits = abap_true
                                               pretty_name      = /ui2/cl_json=>pretty_mode-camel_case ).

    result = original && cl_abap_char_utilities=>cr_lf && open_source.

  ENDMETHOD.

ENDCLASS.
```

Output on my system is still
```json
{"delivery":"1893348   "}
{"delivery":"1893348   "}
```

**Comment by alexey-arseniev** [comment]
Hi Lukas,

Sorry, I did not verify your example initially, I thought that the reason was known, and it is a fixed text buffer that given to the conversion routine and which is than padded with spaces. And that reverting of the code to string buffer, that was planned by me already, will help.

But as I checked now (and you also did) - it is not, and the reason is different. It is the specific conversion exit you use (FM 'CONVERSION_EXIT_ALPHA_OUTPUT'). Even if I provide an empty string buffer it adds padding spaces. Because I do not know, what the business logic of a conversion exit is and if padding spaces are needed or not, I can not simply CONDENSE the output. It may result in other incidents. I would suggest here that you create an SAP message and ask owners of FM CONVERSION_EXIT_ALPHA_OUTPUT to adjust their output logic and not add padding spaces in case they get String as an output. 

But I am still open to further discussion here.

BR, Alexey.

**Comment by bulikd105** [comment]
Hello Alexey,

First of all, thank You very much for developing such a great tool. 
  
Today, I had encountered the same situation as @ElNovi did. 
In our system, we are using PL20 version of this tool.

You mentioned, that You are still open for discussion about this matter and I was thinking a little about how this can be solved.

FM CONVERSION_EXIT_ALPHA_OUTPUT is a standard SAP Conversion Exit, which I guess is very old and will most probably not be changed. 

In this case, I guess that only option is to adjust class /UI2/CL_JSON. 

Would it be possible to add an additional, optional, parameter, to method SERIALIZE?
Such parameter, when set to True, could trigger CONDENSE on the output of conversion exit CONVERSION_EXIT_ALPHA_OUTPUT. 

Please let me know, what do You think about this. 

Best regards,
Damian

**Comment by alexey-arseniev** [comment]
Hi Damian + Lukas,

Yes, it is possible to add an additional customizing flag and have special logic for overcoming bugs in someone else coding :). But it is a bug of FM CONVERSION_EXIT_ALPHA_OUTPUT, at least for cases when it gets STRING as an input. 

I am not a favor of such customizing because: 
- it makes the API of the class more complex and not self-explainable
- it is an additional check in the code, and even if it costs mostly nothing it will be evaluated for each field with conversion exit. 
- I do not want built-in hacks to avoid non-proper handling of foreign code, especially with customizing flag.

Can you please try with a message to SAP first, regarding the correction of the FM CONVERSION_EXIT_ALPHA_OUTPUT?
You may share the message number and I will check with the developer if needed.

BR, Alexey.

**Comment by bulikd105** [comment]
Hi Alexey,

Thank You for your reply.

I had described this issue to my basis team and asked them to create a ticket to our service provider (something like additional support level before SAP) 

I will get back to You as soon as I will get a reply from them. 

Best regards,
Damian

**Comment by bulikd105** [comment]
Hi Alexey,

I got answer from our service provider.

In general, I got sent back to the SAP documentation of FMs CONVERSION_EXIT_ALPHA_INPUT / CONVERSION_EXIT_ALPHA_OUTPUT, where we can find some basic examples of how they work. 

General assumption is that those FMs work as they suppose to work and I should call function 'condense' after getting the result from that FM.

In other words, I got back to the starting point. 

Best regards,
Damian

**Comment by alexey-arseniev** [comment]
Hi Damian,

can you please provide me with a customer message number so that I can check it internally and sync with the developer of the conversion exit? You can also ask your service provider to put the message to the /ui2/cl_json component (BC-FES-BUS-RUN) and I will get it also. 

Let us try to do things right :)

BR, Alexey.

**Comment by mustafaonder** [comment]
Hi @alexey-arseniev,

First of all, thank you for the library and for taking the time to look into this issue in detail.

I just installed the `/UI2/CL_JSON` corrections up to PL23 and noticed that the trailing spaces are still there on my system. I also couldn't find a related change in the `/UI2/CL_JSON==================CCMAC` include in PL19. I'm probably missing something here — as I understood from your earlier comment, the string buffer approach didn't help because `CONVERSION_EXIT_ALPHA_OUTPUT` itself adds the padding, so I wasn't sure whether the issue was closed with a change on the library side or not.

Since you mentioned you're still open to discussion, I tried a small adjustment on my side:

**Before:**

<img width="1403" height="626" alt="Image" src="https://github.com/user-attachments/assets/c649539c-b592-4be3-b198-e5c09cbc6636" />

**The change:**

<img width="819" height="857" alt="Image" src="https://github.com/user-attachments/assets/a5669b72-388b-4fb9-b37b-7ef8fe3bb898" />

<img width="774" height="848" alt="Image" src="https://github.com/user-attachments/assets/3bea69a9-6d40-4745-bee9-9c7cdadc4a98" />

**After:**

<img width="1423" height="543" alt="Image" src="https://github.com/user-attachments/assets/b83bd390-38d5-490f-9f95-391ce091f78a" />

I fully understand your point that the library can't know the business logic behind every conversion exit, and I wouldn't want to cause problems for other users either. Maybe one option could be to apply this only to the ALPHA exit, since trailing spaces there don't carry any meaning? Just an idea — you know the code and its use cases much better than I do, so I'd be happy to hear your thoughts.

Thanks again!
