### ISSUE TITLE
Serialization Optimization potential

### ISSUE THREAD

**Issue by bpreissler** [SAP/abap-to-json#4]
I have learned a lot on performance by checking this class out but also found a few places where it could be further optimized based on my tests. **Important**: I am testing on ABAP 1909 Developer Edition running on Docker Desktop on Windows 11 with an AMD CPU --> about as far from typical SAP ABAP systems as possible, therefore some conclusions might not apply to real world systems.

- Timestamp conversion to ISO format can be enhanced. Seems that the multiple access to the string with offsets is bad for performance. Using two helper variables (char 15 for normal timestamp char 23 for long version) is much faster. I assume this has to do with the string optimization limitations of the ABAP Kernel.
- Concatenate seems to perform worse if string and character are mixed. Therefore switching from \`string\` literals to 'character' literals for the timestamps, date and time concatenates is faster.
- Added an initial check for cl_abap_typedescr=>typekind_char (outside of boolean) to avoid calling the escape logic for empty values.
- Added a check to escape_json to only escape in case any escape-character is present. This is done with a CA-compare. Since the two-character cr_lf contains the one-character newline we only need to check for those four characters (assumption without knowing it is that cr_lf contains newline on any supported architecture). Will be worse if the majority of escape_json really need to be escaped but I assume that the majority of calls will not need ot be escaped. 

As a rough figure when parsing 50000 sbook entries those updates reduce execution time for me by ~35%. When just parsing a table with timestamps the timestamp optimization reduces the overall runtime by ~25%.

I have a branch with those changes on my fork https://github.com/bpreissler/abap-to-json/tree/Serilaization-Optimizations.

**Comment by alexey-arseniev** [comment]
Hi @bpreissler ,

First of all, thanks a lot for the feedback, analysis, and suggestions! 
Second, sorry for the late reply - I was on vacation, but now I am back :)

Regarding your suggestions:
1. I think the reason for the slow performance on serialization of timestamps is not the cost of string access, but missing string concatenation optimization, which is not applied because the target string is used also as a source. I have corrected that using helper string variables. 
2. The problem with concatenation, IMHO, is not a mixture of types, but in the usage of string literals when they are not necessary. In C++ (ABAP Kernel) strings are allocated on the heap, but text field literals, with a fixed length, are allocated on the stack. Allocation on the heap is much slower than on the stack. But the recommendation is correct. So, I have replaced this usage of string literals and others, where it is not optimal, to use text field literals.
3. 4. Was already corrected by me, but was not published yet. Now the changes are also out.

Can you please validate the latest state and give feedback?
And please share your test report, so that I can use it on my side also.

BR, Alex.

**Comment by bpreissler** [comment]
Hi @alexey-arseniev,

thx a lot for the explanations.

I have uploaded the test class https://github.com/bpreissler/abap-to-json-perf (if you wonder I have updated/modified my /ui2/cl_json to be on the current PL18 update so that I can use this as comparison to my z_ui2_json changes).

Regarding point 2 & 3 that looks good for me, too.
Point 1 - the timestamps ... at least in my environment the difference between the helper variable you introduced and c(15) / c(23) fields is still massive for me with ~25% on my timestamp table test. Maybe the string optimization is just not working properly in my environment.

Regards,
Bastian

**Comment by alexey-arseniev** [comment]
Hi Bastian,

thanks for the test report! I was able to validate the change and see that you are right. Working with text fields helper variables is much faster compared to strings. 

I have updated the code and pushed a new version. Please validate. 

BR, Alex.

**Comment by bpreissler** [comment]
Hi Alex,
looks great, also works for me. 
The only last thing that comes to my mind would be to move the conversion logic determination up to the structure element type determination so that all the checks on type and conversion settings are done only once. That way a bunch of IF's would be skipped and there would be less options for the case statement. However as those should be quite fast I assume this would maybe lead to a lower one-digit improvement at the cost of a lot of added complexity which like doesn't make it worth going for.

I think we can therefore close this issue. 

Regards,
Bastian

**Comment by alexey-arseniev** [comment]
Hi Bastian,

Yes, you are right, the conversion detection can be taken out and recalculated for structures. This will bring benefits for big tables. 
I have done it (pushed it to the main), please verify. Your report shows significant improvements. 

BR, Alexey.

**Comment by bpreissler** [comment]
Wow, the difference is bigger than I expected. Great :) No more ideas to speed the serialization up.
