### ISSUE TITLE
ABAP for Cloud Compatibility

### ISSUE THREAD

**Issue by oblomov-dev** [SAP/abap-to-json#6]
Hello everyone,

Thank you for this very nice project and idea!

I'm considering using it for my project to ensure compatibility with older systems that do not include /ui2/cl_json, and this seems to be exactly what I've been searching for.

You can find more details in this issue:
https://github.com/abap2UI5/abap2UI5/issues/807

However, I also need to ensure steampunk readiness.

Are there any plans to make this project ABAP for Cloud ready?

Best regards!

**Comment by alexey-arseniev** [comment]
Hi,

Sorry, I do not understand what the issue is... 

This project is a Open Source variant of the /ui2/cl_json. E.g. same code, managed by the same person, which helps consumers contribute to /ui2/cl_json and get updates faster. 

/ui2/cl_json is released for ABAP for Cloud (Steampunk). 
Current mi requreiemt for /ui2/cl_json code is SAP_BASIS 7.31. If you take versions earlier than PL16 you can use is from SAP_BASIS 700.

What do you want? Release of the Z class (Z_UI2_JSON) for ABAP for Cloud?
Or adoption of the code that it can be used in Steampunk as a Z class (e.g. replace macros, remove RTTI, etc.)?

BR, Alexey.

**Comment by oblomov-dev** [comment]
Yes i am looking for a json parser which is running everywhere (Standard ABAP, ABAP for Cloud).

Your project is exactly what i need, because on some old on-premise SAP systems /ui2/cl_json is unfortunately not available. For example here: https://github.com/abap2UI5/abap2UI5/issues/807

That's why i have in mind to switch from /ui2/cl_json to z_ui2_json.

The problem now is the following:

When i switch to z_ui2_json i can not use it on ABAP for Cloud anymore, because of the macros etc. (RTTI is fine). So yes i am looking for this:
```
Or adoption of the code that it can be used in Steampunk as a Z class (e.g. replace macros, remove RTTI, etc.)?
```

As long as i use /ui2/cl_json in BTP ABAP Environment it runs with all macros because it is in the SAP environment, but as soon as i switch to z_ui2_json on BTP ABAP Environment, i can not use it there, because of the reduced language scope.

Best regards.

**Comment by alexey-arseniev** [comment]
If customers do not have /ui2/cl_json on their system, they need to install UI-Addon to get it. It is from 700. But not sure what is yet officially supported.

Macroses in the class are used because of the performance (method calls are too expensive and ABAP does not support inlining). Removing them in standard will significantly drop performance. But you may do a fork and replace them in your copy.

**Comment by everton-demo** [comment]
Hi @alexey-arseniev , I don't know if it's the best approach to answer the question here, but as it's related to the project mentioned by @oblomov-dev , I'll try.

I understand that this abap-to-json project is an alternative to /UI2/CL_JSON. I use an environment at the company where I work, with version 7.31, where we do not have the UI addon installed. We do not have objects from the /UI2/NWBC_CORE package.
I tried to install the abap-to-json project in this environment, but I had problems because it used objects from this package, such as the /UI2/CL_DATA_ACCESS class.
![image](https://github.com/SAP/abap-to-json/assets/13936273/3d2c8f84-155b-4aba-b450-be04b4aa6c57)

Even though it is an alternative to /UI2/CL_JSON, is it still a requirement to have it, through the UI addon?
Thanks

**Comment by alexey-arseniev** [comment]
Hi @everton-demo,

thanks for reporting! I have missed that - it is a "bug". I will try to solve it (include a z copy of the data access class or replace it with a dynamic call). The /ui2/cl_data_access is used only in unit tests, and I missed that when adopting the /ui2/cl_json class.

Will post the correction soon.

BR, Alexey.

**Comment by oblomov-dev** [comment]
@alexey-arseniev thank you for the information, especially why macros are used. but i think then refactoring on my side to make it steampunk compatible makes no sense, because we would lose one key benefit of this parser.

and also thank you for the bugfix for lower releases!

**Comment by alexey-arseniev** [comment]
@oblomov-dev I will be happy to help if it would go without regression for other consumers. In general open to suggestions and ideas, so if you have some other wishes that are doable, please come back :)

**Comment by oblomov-dev** [comment]
hi @alexey-arseniev yes thanks for the information and the offer! If anything else comes up, I'll reach out :)

**Comment by alexey-arseniev** [comment]
Hi @everton-demo,

I have removed the dependency to /ui2/cl_data_access and added Open Source of it to the package. 
Can you please retry?

BR, Alexey.

**Comment by everton-demo** [comment]
Hi @alexey-arseniev , now I see the following error:
![image](https://github.com/SAP/abap-to-json/assets/13936273/4fec97d5-4657-4ae1-96f6-e97e82c1ad0b)

Thanks

**Comment by alexey-arseniev** [comment]
Hi @everton-demo,

please, next time double-click on the issue, and do the screenshot of the code also. 
I have tried to clean up further issues in the unit tests.

Can you please re-check?

BR, Alexey.

**Comment by everton-demo** [comment]
Hi, good news, everything looks good.

I copied the ABAP to JSON usage example mentioned here https://github.com/SAP/abap-to-json/blob/main/docs/basic.md and got the same return:
![image](https://github.com/SAP/abap-to-json/assets/13936273/f784778c-f702-4a36-8a84-8cb4403eb72c)

Thanks!
